### ISSUE TITLE
SQL Server Profiler Extension

### ISSUE THREAD

**Issue by madelinemacd** [Microsoft/sqlopsstudio#1545]
### Bug fixes
- [x] Fix toolbar spacing
- [x] Change the icon when toggling autoscroll
- [ ] Fix text highlighting after selecting event with empty cells
### Work Items
- [ ] Connect/Disconnect button
- [ ] Auto start profiling when connecting
- [x] Prompt user to close session when exiting
- [ ] Edit columns dialog
- [x] Keyboard shortcuts
- [x] Profiling Azure instances
### Session templates
- [x] View Templates
- [ ] Available session drop down
- [ ] Connect to an existing session
- [ ] Create a new session dialog

**Comment by erkdobey** [comment]
This is a great start to be able to profile Azure.  Will additional configuration be added such as the ability to select specific events (like the current SQL Server Profiler) like SP:StmtStarting so we can get a deaper view into what is occurring which I commonly use when tracking down issues.

**Comment by madelinemacd** [comment]
@erkdobey Yes, that's the plan! Currently the roadmap for the profiler is to allow custom profiler sessions to be created in 2 ways, by connecting the profiler to existing XEvent sessions and by letting you define your own session create statements in a custom session template. We don't have plans right now to create a wizard for custom sessions, like SSMS does.

Both of those custom session ideas would require you to write your own T-SQL for creating your XEvent session, and then from there you could use the profiler extension to display events and manage starting and stopping the session. As of the July public preview we added ability to define your own view settings, so if you need to make changes to capture data from your custom session you can change that in the user settings for SQL Ops.

Development on this is in progress, we're targeting having these features out for the August public preview release, but if you want them sooner they'll probably be available in insider releases first. If you have any other questions or suggestions feel free to open up new issues, I'd love to hear any feedback you have on the extension!
